

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."UrlSummery" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "caption" "text",
    "summery" "text",
    "html" "text",
    "url_id" bigint NOT NULL
);


ALTER TABLE "public"."UrlSummery" OWNER TO "postgres";


COMMENT ON TABLE "public"."UrlSummery" IS 'for a specific url the sammerization data';



ALTER TABLE "public"."UrlSummery" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."UrlSammery_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Urls" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "url" "text",
    "caption" "text"
);


ALTER TABLE "public"."Urls" OWNER TO "postgres";


COMMENT ON TABLE "public"."Urls" IS 'the url to explore';



ALTER TABLE "public"."Urls" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Urls_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."UrlSummery"
    ADD CONSTRAINT "UrlSammery_pkey" PRIMARY KEY ("id", "url_id");



ALTER TABLE ONLY "public"."Urls"
    ADD CONSTRAINT "Urls_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."UrlSummery"
    ADD CONSTRAINT "UrlSammery_url_id_fkey" FOREIGN KEY ("url_id") REFERENCES "public"."Urls"("id");



ALTER TABLE "public"."UrlSummery" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Urls" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."UrlSummery" TO "anon";
GRANT ALL ON TABLE "public"."UrlSummery" TO "authenticated";
GRANT ALL ON TABLE "public"."UrlSummery" TO "service_role";



GRANT ALL ON SEQUENCE "public"."UrlSammery_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."UrlSammery_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."UrlSammery_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Urls" TO "anon";
GRANT ALL ON TABLE "public"."Urls" TO "authenticated";
GRANT ALL ON TABLE "public"."Urls" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Urls_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Urls_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Urls_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























RESET ALL;
